// Turns docs/design-reference/spec/*.json (from capture-frames.mjs) into one
// readable docs/design-reference/spec.md: per frame, one row per element with
// the properties a build phase has to reproduce. Font shorthand is condensed
// to "family weight style size/lineheight" so a row reads like the canvas's
// own inline `font:` declaration.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../..");
const SPEC = join(ROOT, "docs/design-reference/spec");

const fam = (f) => (f.includes("Instrument") ? "Serif" : f.includes("Hanken") ? "Sans" : f.split(",")[0]);
const px = (v) => (v && v !== "normal" && v !== "auto" ? v.replace(/(\.\d\d)\d+px/, "$1px") : "");
const rgb = (c) => (c === "rgba(0, 0, 0, 0)" ? "" : c);
const nz = (v) => (v && v !== "0px" && v !== "none" && v !== "normal" ? v : "");

function fontOf(s) {
  const style = s.fontStyle === "italic" ? " italic" : "";
  return `${fam(s.fontFamily)} ${s.fontWeight}${style} ${px(s.fontSize)}/${px(s.lineHeight)}${nz(s.letterSpacing) ? " ls " + px(s.letterSpacing) : ""}${s.textTransform === "uppercase" ? " UPPER" : ""}`;
}

function animOf(s) {
  if (!s.animationName || s.animationName === "none") return "";
  return `${s.animationName} ${s.animationDuration} ${s.animationDelay}${s.animationIterationCount === "infinite" ? " ∞" : ""}`;
}

function radiusOf(s) {
  const r = s.borderRadius;
  return r && r !== "0px" ? r : "";
}

async function main() {
  const files = (await readdir(SPEC)).filter((f) => f.endsWith(".json")).sort();
  let md = `# Design spec — transcribed from the Golden Hour canvases\n\nGenerated by \`scripts/design-reference/build-spec-md.mjs\` from the computed styles of every rendered frame. Do not hand-edit; re-run \`capture-frames.mjs\` then this script.\n\nColumns: **y** = px from frame top (unrolled), **box** = w×h, **font** = family weight [italic] size/line-height [ls letter-spacing] [UPPER], **anim** = name duration delay.\n\n`;
  for (const file of files) {
    const s = JSON.parse(await readFile(join(SPEC, file), "utf8"));
    md += `## ${file.replace(".json", "")}\n\n_${s.canvas} · ${s.width}px wide · ${s.scrollHeight}px tall · ${s.elements.length} elements_\n\n`;
    md += `| y | box | tag | text | font | color | bg | radius | anim |\n|---:|---|---|---|---|---|---|---|---|\n`;
    for (const e of s.elements) {
      const st = e.style;
      const text = (e.text ?? e.placeholder ?? (e.src ? `img ${e.src.split("/").pop().split("?")[0]}` : "")).replace(/\|/g, "\\|");
      const bg = rgb(st.backgroundColor) || (st.backgroundImage !== "none" ? "gradient/img" : "");
      md += `| ${e.box.y} | ${e.box.w}×${e.box.h} | ${e.tag} | ${text} | ${e.tag === "img" ? "" : fontOf(st)} | ${e.tag === "img" ? "" : st.color} | ${bg} | ${radiusOf(st)} | ${animOf(st)} |\n`;
    }
    md += "\n";
  }
  await writeFile(join(ROOT, "docs/design-reference/spec.md"), md);
  console.log(`spec.md: ${files.length} frames, ${md.length} chars`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
